name: ✨ Feature Request
description: Propose a new feature or enhancement to the existing code.
title: "[FEAT] Brief feature description"
labels: ["type: feature", "status: backlog", "priority: p1"]
body:
  - type: textarea
    id: feature-details
    attributes:
      label: "Detailed Proposal"
      description: Please provide a detailed proposal for this feature.
    validations:
      required: true
