name: ✨ Feature Request
description: Propose a new feature or enhancement to the existing code.
title: "[FEAT] Brief feature description"
labels: ["type: feature", "status: backlog", "priority: p1"]
body:
  - type: textarea
    id: problem
    attributes:
      label: "Problem or Goal"
      description: Explain what problem this feature solves or what its main objective is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: Describe how this feature will be implemented or what changes are expected.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: What must be true for this feature to be considered complete?
    validations:
      required: true
